const String anonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4dnRpdnF0Z3dvb3NrY2JqbWhzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczNTMyNTkxMSwiZXhwIjoyMDUwOTAxOTExfQ.525hQ1WlayMN0Oy_yXi9wDEetw3KMS4ZPblpvlrIBCU';

const String profileUrl = 'https://yxvtivqtgwooskcbjmhs.supabase.co';

