const String anonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4dnRpdnF0Z3dvb3NrY2JqbWhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzMjU5MTEsImV4cCI6MjA1MDkwMTkxMX0.T2ThB2rWe0_kh7EJRYqkmI2emKY13QN4erwTWNXsBvA';

const String profileUrl = 'https://yxvtivqtgwooskcbjmhs.supabase.co';
